/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wimbledonapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *BSHC 1A
 * Group 2
 * Student number: 13114310
 * @author Dagnija Kaulina-Brante
 */
public class Betting1 extends javax.swing.JPanel {

    /**
     * Creates new form Betting1
     */
        private String []games = {"Nicolas Almagro-Martin Alund", "Andre Begemann-James Blake", "Steve Darcis-Alejandro Falla", "Simona Halep-Ana Ivanovic"};//array of players
        private String possibeWinner;
        private String userGuest;
        private String game; //day on which is betting placed
	private double stake; //stake and how much could win
	private double win; //winning for user
        private ArrayList<Bett1>gList;// declare array list
        private int count;
        private double sum, sum1, lost, total;
       
    
    public Betting1() {
        initComponents();
        gList = new ArrayList<>();
        count = 0;
        sum=0;
        sum1=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamePanel = new javax.swing.JPanel();
        playerLB = new javax.swing.JLabel();
        playerCBox = new javax.swing.JComboBox();
        amountToBettLB = new javax.swing.JLabel();
        amountToBettTF = new javax.swing.JTextField();
        editBT = new javax.swing.JButton();
        placeBettBT = new javax.swing.JButton();
        searchBT = new javax.swing.JButton();
        deleteBT = new javax.swing.JButton();
        displayBT = new javax.swing.JButton();
        previousBT = new javax.swing.JButton();

        gamePanel.setMaximumSize(new java.awt.Dimension(320, 200));
        gamePanel.setPreferredSize(new java.awt.Dimension(320, 200));
        gamePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        playerLB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        playerLB.setText("Choose Game:");
        playerLB.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                playerLBComponentHidden(evt);
            }
        });
        gamePanel.add(playerLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 118, 27));

        playerCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose game...", "Nicolas Almagro-Martin Alund", "Andre Begemann-James Blake", "Steve Darcis-Alejandro Falla", "Simona Halep-Ana Ivanovic" }));
        playerCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerCBoxActionPerformed(evt);
            }
        });
        gamePanel.add(playerCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 190, -1));

        amountToBettLB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        amountToBettLB.setText("Bet amount:");
        gamePanel.add(amountToBettLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        amountToBettTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountToBettTFActionPerformed(evt);
            }
        });
        gamePanel.add(amountToBettTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 86, -1));

        editBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        editBT.setText("Edit Betting");
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });
        gamePanel.add(editBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 154, -1));

        placeBettBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        placeBettBT.setText("Place Betting");
        placeBettBT.setMaximumSize(new java.awt.Dimension(121, 25));
        placeBettBT.setMinimumSize(new java.awt.Dimension(121, 25));
        placeBettBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBettBTActionPerformed(evt);
            }
        });
        gamePanel.add(placeBettBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 133, -1));

        searchBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchBT.setText("Search");
        searchBT.setMaximumSize(new java.awt.Dimension(77, 25));
        searchBT.setMinimumSize(new java.awt.Dimension(77, 25));
        searchBT.setPreferredSize(new java.awt.Dimension(77, 25));
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });
        gamePanel.add(searchBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        deleteBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deleteBT.setText("Delete");
        deleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTActionPerformed(evt);
            }
        });
        gamePanel.add(deleteBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        displayBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        displayBT.setText("Display games");
        displayBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTActionPerformed(evt);
            }
        });
        gamePanel.add(displayBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 130, -1));

        previousBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        previousBT.setText("View previous bettings");
        previousBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBTActionPerformed(evt);
            }
        });
        gamePanel.add(previousBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gamePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playerLBComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_playerLBComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_playerLBComponentHidden

    private void playerCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerCBoxActionPerformed

    private void amountToBettTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountToBettTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountToBettTFActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
        // TODO add your handling code here:
        if(amountToBettTF.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Please select game and enter bet amount!");
        }
       else if(playerCBox.getSelectedItem().equals("Choose game...")){
                    JOptionPane.showMessageDialog(null, "Please select game!");
        }
        else{  
                    game = (String)playerCBox.getSelectedItem();
                    stake = Double.parseDouble(amountToBettTF.getText());
                    Bett1 b2 = new Bett1(game, stake);
                    b2.setGame(game);
                    b2.setStake(stake);
                    gList.add(b2);
                        JOptionPane.showMessageDialog(null, "Success Adding game between: "+game+" to betting list");
                    count++;
                    playerCBox.setSelectedItem("Choose game...");
                    amountToBettTF.setText("");
           }
         File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        //Use a try statement
        try{
            //creat objects
            outFile = new File("output.dat");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            //write arrayList to file
            oStream.writeObject(gList);
            //close stream
            oStream.close();
        }
        //catch the IOException
        catch(IOException e){
            System.out.println(e);
        }
     
        
        
        
    }//GEN-LAST:event_editBTActionPerformed

    private void placeBettBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBettBTActionPerformed
        // TODO add your handling code here:
    
      possibeWinner = games[(int)(Math.random()*5)];//random number to select a secret word
                        System.out.println(possibeWinner);//print secret word to help with testing
        
       for (int i=0; i<gList.size(); i++){
            if(possibeWinner.equals(gList.get(i).getGame())){
                        win= gList.get(i).getStake()*1;
                            if(win>0){
                                        JOptionPane.showMessageDialog(null, "Congralation You win: "+win+" EUR!\nFor player: "+gList.get(i).getGame());
                                    }
            }

            if (!possibeWinner.equals(gList.get(i).getGame())){
                                        JOptionPane.showMessageDialog(null, "Sorry You loost in game.\n For game:"+gList.get(i).getGame()+"The winner was: "+ possibeWinner);
                                        lost=gList.get(i).getStake();
                                        sum1=sum1+lost;
            }
       }
                    
       sum=sum+win;             
       total=sum-sum1;
                            JOptionPane.showMessageDialog(null, "Total win is: "+ total);
    }//GEN-LAST:event_placeBettBTActionPerformed

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        // TODO add your handling code here:
       game = (String)playerCBox.getSelectedItem();       
        if (playerCBox.getSelectedItem().equals("Choose game...")){
                        JOptionPane.showMessageDialog(null, "Please choose game to search!");
        }
        for(Bett1 a:gList){
            if(game.equalsIgnoreCase(a.getGame())){
         
            JOptionPane.showMessageDialog(null, "Game between: "+a.getGame()+"\nBet amount to game: "+a.getStake());
                       
            }
          
        }

    
    }//GEN-LAST:event_searchBTActionPerformed

    private void deleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTActionPerformed
        // TODO add your handling code here:
       if(playerCBox.getSelectedItem().equals("Choose game...")){
                JOptionPane.showMessageDialog(null, "Please select game to delete!");
       }
       else if (count==0){
                JOptionPane.showMessageDialog(null, "There is no games saved for betting!");
       }
       else{
                game= (String)playerCBox.getSelectedItem();
                for(int i=0; i<gList.size(); i++){
                    if(gList.get(i).getGame().equals(game)){
                        gList.remove(i);
                        count=count-1;
                        JOptionPane.showMessageDialog(null, "The game had been deleted from betting list!");
                        break;
                    }
                  
                }
       }
    }//GEN-LAST:event_deleteBTActionPerformed

    private void displayBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTActionPerformed
        // TODO add your handling code here:
        for(int i=0; i<gList.size(); i++){
            JOptionPane.showMessageDialog(null, "The following details is entered in list: \n Game to place betting: "+gList.get(i).getGame()+"\nWith bet amount of: "+gList.get(i).getStake());
        }
    }//GEN-LAST:event_displayBTActionPerformed

    private void previousBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBTActionPerformed
        // TODO add your handling code here:
         
        
         File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        //use a try statement
        try{
            //create objects
            inFile = new File("output.dat");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            //read arrayList from file
            gList = (ArrayList <Bett1>)oStream.readObject();
            //loop through the ArrayList
            for(Bett1 x:gList){
                //Print the contents of each object
                JOptionPane.showMessageDialog(null,"Player name: "+x.getGame()+"\nWith Stake of: "+x.getStake());
            }
            //close the stream
            oStream.close();
            
        }
        //catch IOException
        catch(IOException | ClassNotFoundException e){
            System.out.println(e);
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_previousBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountToBettLB;
    private javax.swing.JTextField amountToBettTF;
    private javax.swing.JButton deleteBT;
    private javax.swing.JButton displayBT;
    private javax.swing.JButton editBT;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JButton placeBettBT;
    private javax.swing.JComboBox playerCBox;
    private javax.swing.JLabel playerLB;
    private javax.swing.JButton previousBT;
    private javax.swing.JButton searchBT;
    // End of variables declaration//GEN-END:variables
}
