/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wimbledonapp;

/**
 *BSHC 1A
 * Group 2
 * Student number: 13114310
 * @author Dagnija Kaulina-Brante
 */
public class Betting extends javax.swing.JFrame {

     
    /**
     * Creates new form Betting
     */


    public Betting() {
     
     
        initComponents();
       

      
    }

    public Betting(String userName, String userSurname, String userEmail) {
     
    
        initComponents();
       
        nameSurnameLB.setText(userName+" "+userSurname);
       
        emailLB.setText(userEmail);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PlaceBettingON = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        betting1Panel = new javax.swing.JPanel();
        bettingPanel = new javax.swing.JPanel();
        welcomeLB = new javax.swing.JLabel();
        emailLB = new javax.swing.JLabel();
        nameSurnameLB = new javax.swing.JLabel();
        betting2Panel = new javax.swing.JPanel();
        playerBettingRB = new javax.swing.JRadioButton();
        gameBettingRB = new javax.swing.JRadioButton();
        logoLB = new javax.swing.JLabel();
        homeLB = new javax.swing.JLabel();
        backLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(98, 25, 122));
        mainPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainPanel.setMinimumSize(new java.awt.Dimension(400, 500));
        mainPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        betting1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Betting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(51, 153, 0))); // NOI18N
        betting1Panel.setPreferredSize(new java.awt.Dimension(350, 450));

        javax.swing.GroupLayout bettingPanelLayout = new javax.swing.GroupLayout(bettingPanel);
        bettingPanel.setLayout(bettingPanelLayout);
        bettingPanelLayout.setHorizontalGroup(
            bettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bettingPanelLayout.setVerticalGroup(
            bettingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        welcomeLB.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        welcomeLB.setText("Welcome!!!");

        emailLB.setFont(new java.awt.Font("Times New Roman", 2, 10)); // NOI18N
        emailLB.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                emailLBAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        nameSurnameLB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nameSurnameLB.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nameSurnameLBInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        nameSurnameLB.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nameSurnameLBAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        betting2Panel.setPreferredSize(new java.awt.Dimension(320, 200));

        javax.swing.GroupLayout betting2PanelLayout = new javax.swing.GroupLayout(betting2Panel);
        betting2Panel.setLayout(betting2PanelLayout);
        betting2PanelLayout.setHorizontalGroup(
            betting2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        betting2PanelLayout.setVerticalGroup(
            betting2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        PlaceBettingON.add(playerBettingRB);
        playerBettingRB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        playerBettingRB.setText("Place Betting to player");
        playerBettingRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerBettingRBActionPerformed(evt);
            }
        });

        PlaceBettingON.add(gameBettingRB);
        gameBettingRB.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        gameBettingRB.setText("Place Betting to game");
        gameBettingRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameBettingRBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout betting1PanelLayout = new javax.swing.GroupLayout(betting1Panel);
        betting1Panel.setLayout(betting1PanelLayout);
        betting1PanelLayout.setHorizontalGroup(
            betting1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(betting1PanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(playerBettingRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameBettingRB)
                .addGap(332, 332, 332))
            .addGroup(betting1PanelLayout.createSequentialGroup()
                .addGroup(betting1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(betting2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(betting1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, betting1PanelLayout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addGroup(betting1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameSurnameLB, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, betting1PanelLayout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(welcomeLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        betting1PanelLayout.setVerticalGroup(
            betting1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(betting1PanelLayout.createSequentialGroup()
                .addComponent(welcomeLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameSurnameLB, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailLB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(betting1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerBettingRB)
                    .addComponent(gameBettingRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(betting2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(bettingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(betting1Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 340, 354));

        logoLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/logologo1.jpg"))); // NOI18N
        mainPanel.add(logoLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, -1));

        homeLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/home1.jpg"))); // NOI18N
        homeLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLBMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeLBMousePressed(evt);
            }
        });
        mainPanel.add(homeLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        backLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/back real.png"))); // NOI18N
        backLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLBMouseClicked(evt);
            }
        });
        mainPanel.add(backLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLBMouseClicked
        // TODO add your handling code here:
         MainProject myMainProjectGUI= new MainProject();
        myMainProjectGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeLBMouseClicked

    private void backLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLBMouseClicked
        // TODO add your handling code here:
        More myMoreGUI=new More();
        myMoreGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backLBMouseClicked

    private void homeLBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLBMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeLBMousePressed

    private void nameSurnameLBInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nameSurnameLBInputMethodTextChanged
        // TODO add your handling code here:
    
  
        
        
    }//GEN-LAST:event_nameSurnameLBInputMethodTextChanged

    private void emailLBAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_emailLBAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_emailLBAncestorAdded

    private void nameSurnameLBAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nameSurnameLBAncestorAdded
        // TODO add your handling code here:
      
    }//GEN-LAST:event_nameSurnameLBAncestorAdded

    private void playerBettingRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerBettingRBActionPerformed
        // TODO add your handling code here:
        
            Betting.betting2Panel.removeAll();
            Betting.betting2Panel.setVisible(false);
            Betting2 b2= new Betting2();
            b2.setBounds(0,0,340,220);
            Betting.betting2Panel.add(b2);
            Betting.betting2Panel.setVisible(true);
            
            
       
    }//GEN-LAST:event_playerBettingRBActionPerformed

    private void gameBettingRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameBettingRBActionPerformed
        // TODO add your handling code here:
            Betting.betting2Panel.removeAll();
            Betting.betting2Panel.setVisible(false);
            Betting1 b1= new Betting1();
            b1.setBounds(0,0,340,220);
            Betting.betting2Panel.add(b1);
            Betting.betting2Panel.setVisible(true);
    }//GEN-LAST:event_gameBettingRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Betting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Betting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Betting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Betting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Betting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup PlaceBettingON;
    private javax.swing.JLabel backLB;
    private javax.swing.JPanel betting1Panel;
    private static javax.swing.JPanel betting2Panel;
    private javax.swing.JPanel bettingPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel emailLB;
    private javax.swing.JRadioButton gameBettingRB;
    private javax.swing.JLabel homeLB;
    private javax.swing.JLabel logoLB;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameSurnameLB;
    private javax.swing.JRadioButton playerBettingRB;
    private javax.swing.JLabel welcomeLB;
    // End of variables declaration//GEN-END:variables
}
