/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wimbledonapp;
import javax.swing.JOptionPane;

/**
 *BSHC 1A
 * Group 2
 * Student number: 13114310
 * @author Dagnija Kaulina-Brante
 */
public class Betting2 extends javax.swing.JPanel {

    /**
     * Creates new form Betting2
     */
        private String []players = {"Nicolas Almagro", "Martin Alund", "Andre Begemann", "James Blake", "Steve Darcis", "Alejandro Falla"};//array of players
        private String possibeWinner;
        private String userGuest;
	private double stake; //stake and how much could win
	private double win, lost, totalLost, sum, total; //winning for user
        private String name;
        private int count;
        Bett [] arr;

    public Betting2() {
        initComponents();
        arr = new Bett [7];
        count = 0;
        sum=0;
        lost=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerPanel = new javax.swing.JPanel();
        playerLB = new javax.swing.JLabel();
        playerCBox = new javax.swing.JComboBox();
        amountToBettLB = new javax.swing.JLabel();
        amountToBettTF = new javax.swing.JTextField();
        editBT = new javax.swing.JButton();
        placeBettBT = new javax.swing.JButton();
        searchBT = new javax.swing.JButton();
        deleteBT = new javax.swing.JButton();
        clearBT = new javax.swing.JButton();

        playerPanel.setMaximumSize(new java.awt.Dimension(320, 200));
        playerPanel.setPreferredSize(new java.awt.Dimension(320, 200));

        playerLB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        playerLB.setText("Choose Player:");
        playerLB.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                playerLBComponentHidden(evt);
            }
        });

        playerCBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose player...", "Nicolas Almagro", "Martin Alund", "Andre Begemann", "James Blake", "Steve Darcis", "Alejandro Falla" }));
        playerCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerCBoxActionPerformed(evt);
            }
        });

        amountToBettLB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        amountToBettLB.setText("Bet amount:");

        amountToBettTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountToBettTFActionPerformed(evt);
            }
        });

        editBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        editBT.setText("Edit Betting");
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });

        placeBettBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        placeBettBT.setText("Place Betting");
        placeBettBT.setMaximumSize(new java.awt.Dimension(121, 25));
        placeBettBT.setMinimumSize(new java.awt.Dimension(121, 25));
        placeBettBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeBettBTActionPerformed(evt);
            }
        });

        searchBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        searchBT.setText("Search");
        searchBT.setMaximumSize(new java.awt.Dimension(77, 25));
        searchBT.setMinimumSize(null);
        searchBT.setPreferredSize(new java.awt.Dimension(77, 25));
        searchBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTActionPerformed(evt);
            }
        });

        deleteBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deleteBT.setText("Delete");
        deleteBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTActionPerformed(evt);
            }
        });

        clearBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        clearBT.setText("Clear");
        clearBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playerPanelLayout = new javax.swing.GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerPanelLayout.createSequentialGroup()
                        .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerLB, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amountToBettLB))
                        .addGap(17, 17, 17)
                        .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(playerPanelLayout.createSequentialGroup()
                                .addComponent(amountToBettTF, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(playerCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(playerPanelLayout.createSequentialGroup()
                        .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, playerPanelLayout.createSequentialGroup()
                                .addComponent(searchBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteBT, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editBT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(placeBettBT, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(clearBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        playerPanelLayout.setVerticalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerLB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountToBettLB)
                    .addComponent(amountToBettTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBT)
                    .addComponent(placeBettBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBT))
                    .addComponent(clearBT))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(playerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playerLBComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_playerLBComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_playerLBComponentHidden

    private void playerCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerCBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_playerCBoxActionPerformed

    private void amountToBettTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountToBettTFActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_amountToBettTFActionPerformed

    private void placeBettBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeBettBTActionPerformed
                          // TODO add your handling code here:
      
        possibeWinner= players[(int)(Math.random()*5)];//random number to select a secret word
                        System.out.println(possibeWinner);//print secret word to help with testing

        Bett b;
            for (int i=0; i<count; i++){
                        b = arr[i];

                            if(possibeWinner.equals(b.getName())){
                                win=b.getStake()*1.5;
                                    if(win>0){
                                            JOptionPane.showMessageDialog(null, "Congralation You win: "+win+" EUR!\nFor player: "+b.getName());
                                    }
                            }

                            else{
                                            JOptionPane.showMessageDialog(null, "Sorry You loost in game.\n For player:"+arr[i].getName()+"The winner was: "+ possibeWinner);
                                            lost=arr[i].getStake();
                                            totalLost=totalLost+lost;
                            }
            }
                    sum=sum+win;
                    total=sum-totalLost;
                            JOptionPane.showMessageDialog(null, "Total win is: "+ total+" EUR");
        
    }//GEN-LAST:event_placeBettBTActionPerformed

    private void clearBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTActionPerformed
        // TODO add your handling code here:
 
   playerCBox.setSelectedItem("Choose player...");
   amountToBettTF.setText("");
        
        
       
        
    }//GEN-LAST:event_clearBTActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
        // TODO add your handling code here:
        if(amountToBettTF.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Please select player and enter bet amount!");
        }
        else if(playerCBox.getSelectedItem().equals("Choose player...")){
                    JOptionPane.showMessageDialog(null, "Please select player!");
        }
        else{  
            Bett b;
            name = (String)playerCBox.getSelectedItem();
            stake = Double.parseDouble(amountToBettTF.getText());
            b = new Bett(name, stake);

            playerCBox.setSelectedItem("Choose player...");
            amountToBettTF.setText("");

                    JOptionPane.showMessageDialog(null, "Success Adding player: "+name+" to betting list");
            arr[count] = b;
            count++;
        }

    }//GEN-LAST:event_editBTActionPerformed

    private void searchBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTActionPerformed
        // TODO add your handling code here:
      
        name = (String)playerCBox.getSelectedItem();
        Bett b;
        if (name.equals("Choose player...")){
                         JOptionPane.showMessageDialog(null, "You did not select a players name");
        }
        
     
      
        else {
            for (int i=0; i<count; i++){
                b = arr[i];
                    if (name.equals(b.getName())){

                         JOptionPane.showMessageDialog(null, "Player name: "+b.getName()+"\nAmount to bet on player: "+b.getStake());
                       
                    }
                   
            }
        }

    }//GEN-LAST:event_searchBTActionPerformed

    private void deleteBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTActionPerformed
        // TODO add your handling code here:
        name = (String)playerCBox.getSelectedItem();

        int deleteIndex = -1;
        Bett b;

        if (name.equals("Choose player...")){
                        JOptionPane.showMessageDialog(null, "Enter player to delete!!");
        }
      
        else {
            for (int i=0; i<count; i++){
                b = arr[i];
                   if (name.equals(b.getName())){
                            arr[i] = arr[count-1];
                            arr[count-1] = null;
                            count --;
                        JOptionPane.showMessageDialog(null, "Deleting player: "+b.getName()+"\nwith amount to bet: "+b.getStake()+" from the list. "+"\nThere are " + count + " bettings left");
                        break;
                    }
            }
        }

    }//GEN-LAST:event_deleteBTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountToBettLB;
    private javax.swing.JTextField amountToBettTF;
    private javax.swing.JButton clearBT;
    private javax.swing.JButton deleteBT;
    private javax.swing.JButton editBT;
    private javax.swing.JButton placeBettBT;
    private javax.swing.JComboBox playerCBox;
    private javax.swing.JLabel playerLB;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JButton searchBT;
    // End of variables declaration//GEN-END:variables
}
