/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wimbledonapp;

/**
 *
 * @author Sandris
 */
public class MainProject extends javax.swing.JFrame {

    /**
     * Creates new form MainProject
     */
    public MainProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainLogo = new javax.swing.JLabel();
        mainImage = new javax.swing.JLabel();
        mainNewsBtn = new javax.swing.JButton();
        mainResultsBtn = new javax.swing.JButton();
        mainMultmediaBtn = new javax.swing.JButton();
        mainMoreBtn = new javax.swing.JButton();
        mainTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(98, 25, 122));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/logologo1.jpg"))); // NOI18N
        jPanel1.add(mainLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        mainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/Untitled.png"))); // NOI18N
        jPanel1.add(mainImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, -1));

        mainNewsBtn.setText("News");
        mainNewsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainNewsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mainNewsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 90, -1));

        mainResultsBtn.setText("Results");
        mainResultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainResultsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mainResultsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 80, -1));

        mainMultmediaBtn.setText("Multimedia");
        mainMultmediaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMultmediaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mainMultmediaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 100, -1));

        mainMoreBtn.setText("More");
        mainMoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMoreBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mainMoreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 80, -1));

        mainTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mainTitle.setForeground(new java.awt.Color(255, 255, 255));
        mainTitle.setText("Welcome to Wimbledon!");
        jPanel1.add(mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMoreBtnActionPerformed

        // TODO add your handling code here:
        More myMoreGUI= new More();
        myMoreGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainMoreBtnActionPerformed

    private void mainMultmediaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMultmediaBtnActionPerformed
        // TODO add your handling code here:
        MultimediaMainGUI myMultimediaMainGUI= new MultimediaMainGUI();
        myMultimediaMainGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainMultmediaBtnActionPerformed

    private void mainNewsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainNewsBtnActionPerformed
        // TODO add your handling code here:
        News myScheduleGUI= new News();
        myScheduleGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainNewsBtnActionPerformed

    private void mainResultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainResultsBtnActionPerformed
        // TODO add your handling code here:
        Results myResultsGUI= new Results();
        myResultsGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mainResultsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainImage;
    private javax.swing.JLabel mainLogo;
    private javax.swing.JButton mainMoreBtn;
    private javax.swing.JButton mainMultmediaBtn;
    private javax.swing.JButton mainNewsBtn;
    private javax.swing.JButton mainResultsBtn;
    private javax.swing.JLabel mainTitle;
    // End of variables declaration//GEN-END:variables
}
