/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wimbledonapp;

/**
 *BSHC 1A
 * Group 2
 * Student number 13114310
 * @author Dagnija Kaulina-Brante
 */
public class More extends javax.swing.JFrame {

    /**
     * Creates new form More
     */
    public More() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homePanel = new javax.swing.JPanel();
        weatherForecastBT = new javax.swing.JButton();
        bettingBT = new javax.swing.JButton();
        bookTicketsBT = new javax.swing.JButton();
        logoLB = new javax.swing.JLabel();
        homeLB = new javax.swing.JLabel();
        mainPictureLB = new javax.swing.JLabel();
        bannerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        backLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homePanel.setBackground(new java.awt.Color(98, 25, 122));
        homePanel.setMaximumSize(new java.awt.Dimension(400, 500));
        homePanel.setPreferredSize(new java.awt.Dimension(400, 500));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        weatherForecastBT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        weatherForecastBT.setText("Weather");
        weatherForecastBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weatherForecastBTActionPerformed(evt);
            }
        });
        homePanel.add(weatherForecastBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 126, -1));

        bettingBT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bettingBT.setText("Betting");
        bettingBT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bettingBTItemStateChanged(evt);
            }
        });
        bettingBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bettingBTActionPerformed(evt);
            }
        });
        bettingBT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bettingBTKeyPressed(evt);
            }
        });
        homePanel.add(bettingBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 127, -1));

        bookTicketsBT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bookTicketsBT.setText("Book Tickets");
        bookTicketsBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketsBTActionPerformed(evt);
            }
        });
        homePanel.add(bookTicketsBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 121, -1));

        logoLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/logologo1.jpg"))); // NOI18N
        homePanel.add(logoLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        homeLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/home1.jpg"))); // NOI18N
        homeLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLBMouseClicked(evt);
            }
        });
        homePanel.add(homeLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        mainPictureLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/Untitled.png"))); // NOI18N
        homePanel.add(mainPictureLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        bannerPanel.setBackground(new java.awt.Color(1, 103, 55));
        bannerPanel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bannerPanel.setPreferredSize(new java.awt.Dimension(340, 60));

        jLabel1.setBackground(new java.awt.Color(51, 153, 0));
        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("More");

        javax.swing.GroupLayout bannerPanelLayout = new javax.swing.GroupLayout(bannerPanel);
        bannerPanel.setLayout(bannerPanelLayout);
        bannerPanelLayout.setHorizontalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerPanelLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        bannerPanelLayout.setVerticalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        homePanel.add(bannerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 340, 60));

        backLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/back real.png"))); // NOI18N
        backLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLBMouseClicked(evt);
            }
        });
        homePanel.add(backLB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bettingBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bettingBTActionPerformed
        // TODO add your handling code here:
        Login myLoginGUI= new Login();
        myLoginGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bettingBTActionPerformed

    private void weatherForecastBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weatherForecastBTActionPerformed
        // TODO add your handling code here:
        WeatherForecast myWeatherForecastGUI= new WeatherForecast();
        myWeatherForecastGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_weatherForecastBTActionPerformed

    private void bettingBTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bettingBTKeyPressed
       
// TODO add your handling code here:a
        
        
    }//GEN-LAST:event_bettingBTKeyPressed

    private void bettingBTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bettingBTItemStateChanged
        // TODO add your handling code here:
     
    }//GEN-LAST:event_bettingBTItemStateChanged

    private void homeLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLBMouseClicked
        // TODO add your handling code here:
        MainProject myMainProjectGUI= new MainProject();
        myMainProjectGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeLBMouseClicked

    private void bookTicketsBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketsBTActionPerformed
        // TODO add your handling code here:
        Login myLoginGUI= new Login();
        myLoginGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bookTicketsBTActionPerformed

    private void backLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLBMouseClicked
        // TODO add your handling code here:
        MainProject myMainProjectGUI= new MainProject();
        myMainProjectGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backLBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(More.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(More.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(More.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(More.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new More().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLB;
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JButton bettingBT;
    private javax.swing.JButton bookTicketsBT;
    private javax.swing.JLabel homeLB;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logoLB;
    private javax.swing.JLabel mainPictureLB;
    private javax.swing.JButton weatherForecastBT;
    // End of variables declaration//GEN-END:variables
}
