
package wimbledonapp;

/**
 *BSHC 1A
 *Group 2
 *@author Daniel Benhamou x13341086
 */
public class MultimediaMainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MultimediaMainGUI
     */
    public MultimediaMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagesBtnMain = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        multimediaBanner = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        videoBtnMain = new javax.swing.JButton();
        quizBtnMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(98, 25, 122));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagesBtnMain.setText("Images");
        imagesBtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagesBtnMainActionPerformed(evt);
            }
        });
        jPanel1.add(imagesBtnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 97, 98));

        jPanel2.setBackground(new java.awt.Color(1, 103, 55));

        multimediaBanner.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        multimediaBanner.setForeground(new java.awt.Color(255, 255, 255));
        multimediaBanner.setText("Multimedia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(multimediaBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(multimediaBanner)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 11, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/home1.jpg"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 381, 67, 65));

        videoBtnMain.setText("Video");
        videoBtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoBtnMainActionPerformed(evt);
            }
        });
        jPanel1.add(videoBtnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 98, 98));

        quizBtnMain.setText("Quiz");
        quizBtnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBtnMainActionPerformed(evt);
            }
        });
        jPanel1.add(quizBtnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 97, 98));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imagesBtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagesBtnMainActionPerformed
        // TODO add your handling code here:
        MultimediaImageGUI myMultimediaImageGUI= new MultimediaImageGUI();
        myMultimediaImageGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_imagesBtnMainActionPerformed

    private void videoBtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoBtnMainActionPerformed
        // TODO add your handling code here:
        MultimediaVideoGUI myMultimediaVideosGUI= new MultimediaVideoGUI();
        myMultimediaVideosGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_videoBtnMainActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        MainProject myMainProject = new MainProject();
        myMainProject.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void quizBtnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBtnMainActionPerformed
        // TODO add your handling code here:
        MultimediaQuiz myMultimediaQuiz = new MultimediaQuiz();
        myMultimediaQuiz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_quizBtnMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultimediaMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultimediaMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultimediaMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultimediaMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultimediaMainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton imagesBtnMain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel multimediaBanner;
    private javax.swing.JButton quizBtnMain;
    private javax.swing.JButton videoBtnMain;
    // End of variables declaration//GEN-END:variables
}
