/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wimbledonapp;



/**
 *BSHC 1A
 *Group 2
 *@author Daniel Benhamou x13341086
 */
public class MultimediaImageGUI extends javax.swing.JFrame {

    /**
     * Creates new form MultimediaGUI
     */
    public MultimediaImageGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        videoLink = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        imageLink4 = new javax.swing.JButton();
        imageLink1 = new javax.swing.JButton();
        imageLink2 = new javax.swing.JButton();
        imageLink3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        imageTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(98, 25, 122));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        videoLink.setText("Videos");
        videoLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoLinkActionPerformed(evt);
            }
        });
        jPanel1.add(videoLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, -1, -1));

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/home1.jpg"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 67, 65));

        imageLink4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/thumbnail1.jpg"))); // NOI18N
        imageLink4.setMaximumSize(new java.awt.Dimension(430, 310));
        imageLink4.setMinimumSize(new java.awt.Dimension(430, 310));
        imageLink4.setPreferredSize(new java.awt.Dimension(430, 310));
        imageLink4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageLink4ActionPerformed(evt);
            }
        });
        jPanel1.add(imageLink4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 170, 140));

        imageLink1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/thumbnail4.jpg"))); // NOI18N
        imageLink1.setMaximumSize(new java.awt.Dimension(430, 310));
        imageLink1.setMinimumSize(new java.awt.Dimension(430, 310));
        imageLink1.setPreferredSize(new java.awt.Dimension(430, 310));
        imageLink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageLink1ActionPerformed(evt);
            }
        });
        jPanel1.add(imageLink1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 140));

        imageLink2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/thumbnail3.jpg"))); // NOI18N
        imageLink2.setMaximumSize(new java.awt.Dimension(430, 310));
        imageLink2.setMinimumSize(new java.awt.Dimension(430, 310));
        imageLink2.setPreferredSize(new java.awt.Dimension(430, 310));
        imageLink2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageLink2ActionPerformed(evt);
            }
        });
        jPanel1.add(imageLink2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 170, 140));

        imageLink3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/thumbnail2.jpg"))); // NOI18N
        imageLink3.setMaximumSize(new java.awt.Dimension(430, 310));
        imageLink3.setMinimumSize(new java.awt.Dimension(430, 310));
        imageLink3.setPreferredSize(new java.awt.Dimension(430, 310));
        imageLink3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageLink3ActionPerformed(evt);
            }
        });
        jPanel1.add(imageLink3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 170, 140));

        jPanel2.setBackground(new java.awt.Color(1, 103, 55));

        imageTitle.setBackground(new java.awt.Color(1, 103, 55));
        imageTitle.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        imageTitle.setForeground(new java.awt.Color(255, 255, 255));
        imageTitle.setText("Images");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(imageTitle)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 220, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void videoLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoLinkActionPerformed
        // TODO add your handling code here:
      MultimediaVideoGUI myMultimediaVideosGUI= new MultimediaVideoGUI();
      myMultimediaVideosGUI.setVisible(true);
      this.dispose();
      
    }//GEN-LAST:event_videoLinkActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        MainProject myMainProject = new MainProject();
        myMainProject.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void imageLink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageLink1ActionPerformed
        // TODO add your handling code here:
      ImagePage myImagePage= new ImagePage();
      myImagePage.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_imageLink1ActionPerformed

    private void imageLink2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageLink2ActionPerformed
        // TODO add your handling code here:
      ImagePageOne myImagePageOne= new ImagePageOne();
      myImagePageOne.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_imageLink2ActionPerformed

    private void imageLink4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageLink4ActionPerformed
        // TODO add your handling code here:
      ImagePageThree myImagePageThree = new ImagePageThree();
      myImagePageThree.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_imageLink4ActionPerformed

    private void imageLink3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageLink3ActionPerformed
        // TODO add your handling code here:
      ImagePageTwo myImagePageTwo = new ImagePageTwo();
      myImagePageTwo .setVisible(true);
      this.dispose();
    }//GEN-LAST:event_imageLink3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultimediaImageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultimediaImageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultimediaImageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultimediaImageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultimediaImageGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton imageLink1;
    private javax.swing.JButton imageLink2;
    private javax.swing.JButton imageLink3;
    private javax.swing.JButton imageLink4;
    private javax.swing.JLabel imageTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton videoLink;
    // End of variables declaration//GEN-END:variables
}
