/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wimbledonapp;

/**
 * BSHC 1A
 * Group 2
 * Student number: 13114310
 * @author Dagnija Kaulina-Brante
 * section more
 */
public class Tuesday extends javax.swing.JPanel {

    /**
     * Creates new form Tuesday
     */
    public Tuesday() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tuesdayLB = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(110, 120));
        setMinimumSize(new java.awt.Dimension(110, 120));
        setPreferredSize(new java.awt.Dimension(110, 120));

        tuesdayLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/weather tuesday.JPG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tuesdayLB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tuesdayLB)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel tuesdayLB;
    // End of variables declaration//GEN-END:variables
}
