/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wimbledonapp;

/**
 * BSHC 1A
 * Group 2
 * Student number: 13114310
 * @author Dagnija Kaulina-Brante
 * section more
 */
public class Wednesday extends javax.swing.JPanel {

    /**
     * Creates new form Wednesday
     */
    public Wednesday() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wednesdayLB = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(110, 120));

        wednesdayLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wimbledonapp/weather wednesday.JPG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wednesdayLB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wednesdayLB)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel wednesdayLB;
    // End of variables declaration//GEN-END:variables
}
